version: '3'
services:
  gateway:
    image: nginx:1.19.4
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf

  frontend:
    build: webapp

  backend:
    build: service
    environment:
      - REDIS_HOST=redis

  redis:
    image: redis:6.0.9

