version: '3'
services:
  gateway:
    image: nginx:1.19.4
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf

  frontend:
    build:
      context: webapp
      args:
        - API_SERVER=/api

  backend:
    build: service
