name: Service CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    working-directory: ./service

jobs:
  check_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - env:
        FBCONFIG_TEST: ${{ secrets.FBCONFIG_TEST }}
      run: echo "$FBCONFIG_TEST" | base64 -d > fbConfigs_test.json

    - env:
        ENVIRON_JSON: ${{ secrets.ENVIRON_JSON }}
      run: echo "$ENVIRON_JSON" | base64 -d > environ.json

    - run: pip install -r requirements.txt

    - run: flake8 . --max-line-length=99

    - run: pylint --disable=C0415,C0103 utils models routes

    - run: pytest
